server:
  port: 8686

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/api/items/
        - id: order-service
          uri: lb://order-service
          predicates:
              - Path=/api/orders/**, /api/carts/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
              - Path=/api/customers/
        - id: okta-service
          uri: lb://okta-service
          predicates:
              - Path=/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true

